[package]
name = "runtime"
version = "0.1.0"
authors = ["Jin Mingjian <jin.phd@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
base = { path = "../base" }
ir = { path = "../ir" }
lazy_static = "1.4"

[build-dependencies]
base = { path = "../base" }