[package]
name = "base"
version = "0.1.0"
authors = ["Jin Mingjian"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
base_proc_macro = { path = "./proc_macro" }
itoa = "0.4"
dtoa = "0.4"
thiserror = "1.0"

[[bench]]
name = "bench_syscalls"
harness = false
