name: Base Integ Sanity Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
    - name: TensorBase Run server
      run: |
           mkdir ${{ github.workspace }}/tb_data
           cargo run --bin server -- -s "$BASE_CONF"
