name: TensorBase Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: TensorBase Build
      run: CARGO_PROFILE_RELEASE_LTO='thin' CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 cargo build --release
    - name: TensorBase Archive
      run: zip -j base_linux.zip target/release/server crates/server/tests/confs/base.conf
    - name: TensorBase Create Release
      uses: anton-yurchenko/git-release@v3.4.4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "true"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_SUFFIX: " (nightly build)"
      with:
        args: |
          base_linux.zip

    
